P3_DESKTOP_VERSION = 1.0
P3_DESKTOP_SITE = $(BR2_EXTERNAL_P3LINUX_PATH)/package/p3-desktop/src
P3_DESKTOP_SITE_METHOD = local
P3_DESKTOP_LICENSE = MIT
P3_DESKTOP_DEPENDENCIES = fltk
define P3_DESKTOP_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D) CXX="$(TARGET_CXX)" \
		CXXFLAGS="$(TARGET_CXXFLAGS)" LDFLAGS="$(TARGET_LDFLAGS)" \
		FLTK_CONFIG="$(STAGING_DIR)/usr/bin/fltk-config"
endef
define P3_DESKTOP_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) DESTDIR=$(TARGET_DIR) install
endef
$(eval $(generic-package))
